"""empty message

Revision ID: 90f556a9fa24
Revises: 
Create Date: 2020-01-25 16:53:38.025532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f556a9fa24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('zip', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fc_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['fc_id'], ['fc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('van',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fc_id', sa.Integer(), nullable=True),
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.ForeignKeyConstraint(['fc_id'], ['fc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vin')
    )
    op.create_table('wave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fc_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fc_id'], ['fc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('van_id', sa.Integer(), nullable=True),
    sa.Column('wave_id', sa.Integer(), nullable=True),
    sa.Column('scan_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['van_id'], ['van.id'], ),
    sa.ForeignKeyConstraint(['wave_id'], ['wave.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('wave')
    op.drop_table('van')
    op.drop_table('user')
    op.drop_table('fc')
    # ### end Alembic commands ###
